version: "3"
services: 
  web:
    build: .
      context: .
    image: nginx:1.18
    container_name: 'c-nginx'
    restart: unless-stopped
    ports:
      - 80:80
    command:
      nginx -g 'daemon off; '  